using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mittons.Messaging.Email.SourceGenerator;

[Generator]
public class TemplateExtensionMethodGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "Mittons.Messaging.Email.EmailTemplateAttribute",
            predicate: static (syntaxNode, cancellationToken)
                => syntaxNode is ClassDeclarationSyntax,
            transform: static (context, cancellationToken) =>
            {
                var model = new Model(
                    context.TargetSymbol.ContainingNamespace.ToDisplayString(),
                    context.TargetSymbol.Name,
                    string.Join(",", (context.TargetSymbol as INamedTypeSymbol)?.GetMembers()
                        .OfType<IPropertySymbol>()
                        .SelectMany(p => p.GetAttributes().Select(a => a.AttributeClass?.ToDisplayString()))
                    ),
                    [..
                        context.TargetSymbol
                            .GetAttributes()
                            .Where(a => a.AttributeClass?.ToDisplayString() == "Mittons.Messaging.Email.EmailTemplateAttribute")
                            .Select(a => a.ConstructorArguments.First().Value!.ToString())
                            .Distinct()
                    ],
                    []
                );

                if (context.TargetSymbol is INamedTypeSymbol classSymbol)
                {
                    var properties = classSymbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Microsoft.AspNetCore.Components.ParameterAttribute"));

                    foreach (var property in properties)
                    {
                        model.Parameters[property.Name] = property.Type.ToDisplayString();
                    }
                }

                return model;
            }
        );

        context.RegisterPostInitializationOutput(static postInitializationContext => {
            postInitializationContext.AddEmbeddedAttributeDefinition();
            postInitializationContext.AddSource("myGeneratedFile.cs", SourceText.From("""
                using System;
                using Microsoft.CodeAnalysis;

                namespace Mittons.Messaging.Email
                {
                    [Embedded]
                    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                    public sealed class EmailTemplateAttribute(string templateName) : Attribute
                    {
                        public string TemplateName { get; set; } = templateName;
                    }
                }
                """, Encoding.UTF8));
        });

        context.RegisterSourceOutput(provider, static (context, model) =>
        {
            var sourceText = SourceText.From($$"""
            // <auto-generated />
            using Mittons.Messaging.Email.Models;
            using Mittons.Messaging.Email.Services;
            using MimeKit;
            using System.Collections.Generic;
            using System.Linq;
            using System.Threading;
            using System.Threading.Tasks;

            using {{model.Namespace}};

            #nullable enable
            namespace Mittons.Messaging.Email
            {
                public static class {{model.ClassName}}_EmailServiceExtensions
                {
            {{string.Join(
                "\n\n",
                model.TemplateNames.Select(templateName => GenerateTemplateFunctions(model.ClassName, templateName, model.Parameters))
            )}}
                }
            }

            """, Encoding.UTF8);

            context.AddSource($"{model.ClassName}EmailServiceExtensions.g.cs", sourceText);
        });
    }

    private static string GenerateTemplateFunctions(
        string className,
        string templateName,
        Dictionary<string, string> parameters
    )
    {
        string functionDefinitionArguments = string.Join(
            "",
            parameters.Select(kvp => $"\n            {kvp.Value} {ConvertToCamelCase(kvp.Key)},")
        );
        string functionCallArguments = string.Join(
            "",
            parameters.Select(kvp => $"\n                {ConvertToCamelCase(kvp.Key)}: {ConvertToCamelCase(kvp.Key)},")
        );
        string dictionaryEntries = string.Join(
            "",
            parameters.Select(kvp => $$"""{{"\n"}}                    { "{{kvp.Key}}", {{ConvertToCamelCase(kvp.Key)}} },""")
        );

        return $$"""
                public static Task Send{{templateName}}Async(
                    this IEmailService emailService,{{functionDefinitionArguments}}
                    string subject,
                    string from,
                    IEnumerable<string>? to = default,
                    IEnumerable<string>? cc = default,
                    IEnumerable<string>? bcc = default,
                    IEnumerable<string>? replyTo = default,
                    IEnumerable<Attachment>? attachments = default,
                    CancellationToken cancellationToken = default
                )
                    => emailService.Send{{templateName}}Async({{functionCallArguments}}
                        subject: subject,
                        from: new MailboxAddress(from, from),
                        to: to?.Select(email => new MailboxAddress(email, email)),
                        cc: cc?.Select(email => new MailboxAddress(email, email)),
                        bcc: bcc?.Select(email => new MailboxAddress(email, email)),
                        replyTo: replyTo?.Select(email => new MailboxAddress(email, email)),
                        attachments: attachments,
                        cancellationToken: cancellationToken
                    );

                public static Task Send{{templateName}}Async(
                    this IEmailService emailService,{{functionDefinitionArguments}}
                    string subject,
                    MailboxAddress from,
                    IEnumerable<MailboxAddress>? to = default,
                    IEnumerable<MailboxAddress>? cc = default,
                    IEnumerable<MailboxAddress>? bcc = default,
                    IEnumerable<MailboxAddress>? replyTo = default,
                    IEnumerable<Attachment>? attachments = default,
                    CancellationToken cancellationToken = default
                )
                    => emailService.SendEmailAsync<{{className}}>(
                        subject: subject,
                        from: from,
                        to: to,
                        cc: cc,
                        bcc: bcc,
                        replyTo: replyTo,
                        attachments: attachments,
                        parameters: new Dictionary<string, object?>
                        {{{dictionaryEntries}}
                        },
                        cancellationToken: cancellationToken
                    );
        """;
    }

    private static string ConvertToCamelCase(string content)
        => string.IsNullOrWhiteSpace(content) ? "" : $"{char.ToLower(content.Trim()[0])}{content.Trim().Substring(1)}";

    private record Model(
        string Namespace,
        string ClassName,
        string Temp,
        List<string> TemplateNames,
        Dictionary<string, string> Parameters
    )
    {
        public virtual bool Equals(Model other)
            => (other is not null) && (ReferenceEquals(this, other) || GetHashCode() == other.GetHashCode());

        public override int GetHashCode()
        {
            HashCode hash = new();

            hash.Add(Namespace);
            hash.Add(ClassName);
            hash.Add(Temp);
            TemplateNames.OrderBy(name => name).ToList().ForEach(name => hash.Add(name));

            Parameters.OrderBy(kvp => kvp.Key).ThenBy(kvp => kvp.Value).ToList().ForEach(kvp =>
            {
                hash.Add(kvp.Key);
                hash.Add(kvp.Value);
            });

            return hash.ToHashCode();
        }
    }
}
